config/routes.rb
Rails.application.routes.draw do

devise_for :users
resources :posts

root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @post = Post.all.order("created_at DESC")
  end

  def show

  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      redirect_to root_path
    end
  end

  def destroy
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :link, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Folioh</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        <script src="https://use.fontawesome.com/8ad03d15b0.js"></script>
    </head>
    <body>
        <nav class="main-nav">
            <ul class="site-nav"> 
                <li>
                    <%= link_to "FOLIOH", root_path %>
                </li>
                <li>
                    <%= link_to "Posts", posts_url%>
                </li>
                <% if user_signed_in? %>
                <li>
                    <%= link_to "New Post", new_post_url, class: "cta"%>
                </li>
                <% end %>
            </ul>

            <ul class="main-nav__user-info">

                <% if user_signed_in? %>
                <li>
                    Oh! Hi,
                    <strong><%= link_to current_user.name, edit_user_registration_path %></strong>
                </li>
                <li>
                    <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
                </li>

            <% else %>
                <li>
                    <%= link_to "Sign Up", new_user_registration_path %>
                </li>

                <li>
                    <%= link_to "Login", new_user_session_path %>
                </li>

                <% end%>
            </ul>
        </nav>
        <div class="container">
          <p class="notice" style="color: green; font-weight: bold;"><%= notice %></p>
          <p class="alert" style="color: red; font-weight: bold;"><%= alert %></p>
        </div>
        <div class="main-content">
            <%= yield %>
        </div>
    </body>
</html>

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
  = f.input :title
  = f.input :link
  = f.input :description, :input_html=> { :rows => 20}

  = f.button :submit, class: 'btn success'

app/views/posts/edit.html.haml
%section
  .container
    .wrapper.wrapper
      %h1 Edit Post

      = render 'form'

      .action-block
        = link_to posts_url, class: "btn"do
          %i.fa.fa-long-arrow-left
          back
        = link_to post_path, method: :delete, data: { confirm: "are you sure?" }, class: "btn danger" do
          %i.fa.fa-trash
          delete

app/views/posts/index.html.haml
%section
  .posts.container.flex-grid
    - @post.each do |post|
      .col-1-4
        .post-panel
          = link_to post do
            .post-image
            %h2.post-title= post.title
          .post-data
            %span= post.user.name

app/views/posts/new.html.haml
%section
  .container
    .wrapper
      %h2 New Post
      = render 'form'

app/views/posts/show.html.haml
%section
  .container
    .flex-grid
      .col-2-3
        .wrapper--no-padding
          %h1= @post.title
          %iframe{:src => "//#{@post.link}"}
          %p= @post.user.name
          %p
            =link_to @post.link, "//#{@post.link}", target: "_blank"
          %p= simple_format h @post.description

          - if @post.user == current_user
            .action-block
              .right
                = link_to edit_post_path(@post), class: "btn warning" do
                  %i.fa.fa-pencil
                  edit
                = link_to post_path, method: :delete, data: { confirm: "are you sure?" }, class: "btn danger" do
                  %i.fa.fa-trash
                  delete

              = link_to posts_url, class: "btn"do
                %i.fa.fa-long-arrow-left
                back
      .col-1-3
        .wrapper.wrapper
          .test
            posted #{time_ago_in_words(@post.created_at)}